name: "Build and push"
description: "Build the docker image and push to ECR"

inputs:
  ecr_registry:
    description: "AWS ECR registry"
    required: true
    default: "593673322979.dkr.ecr.us-west-1.amazonaws.com"
  ecr_repository:
    description: "AWS ECR repository"
    required: true
  ecr_region:
    description: "AWS ECR region"
    required: true
    default: "us-west-1"
  aws_ecr_role_arn:
    description: "AWS ECR role"
    required: true
    default: "arn:aws:iam::593673322979:role/github_oidc_role_ecr"
  update_latest:
    description: "Update latest tag"
    required: true
    default: "false"
  dockerfile:
    description: "Dockerfile path"
    required: true
    default: "Dockerfile"
  args:
    description: "Docker build args"
    required: false
    default: ""
  additional_tags:
    description: "Additional tags to add to image"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_ecr_role_arn }}
        aws-region: ${{ inputs.ecr_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and tag Docker image
      shell: bash
      run: |
        IFS=',' read -ra BUILD_ARGS <<< "${{ inputs.args }}"
        BUILD_ARGS_STRING=""
        for ARG in "${BUILD_ARGS[@]}"; do
            BUILD_ARGS_STRING+="--build-arg $ARG "
        done

        docker build -f ${{ inputs.dockerfile }} $BUILD_ARGS_STRING -t ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ github.sha }} .
        if [ "${{ inputs.update_latest }}" = "true" ]; then
          docker tag ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ github.sha }} ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:latest
        fi
        
        if [ "${{ inputs.additional_tags }}" != "" ]; then
          for additional_tag in "${{ inputs.additional_tags }}"; do
            docker tag ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ github.sha }} ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:$additional_tag
          done
        fi

    - name: Push Docker image to ECR
      shell: bash
      run: |
        docker push ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:${{ github.sha }}
        if [ "${{ inputs.update_latest }}" = "true" ]; then
          docker push ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:latest
        fi
        if [ "${{ inputs.additional_tags }}" != "" ]; then
          for additional_tag in "${{ inputs.additional_tags }}"; do
            docker push ${{ inputs.ecr_registry }}/${{ inputs.ecr_repository }}:$additional_tag
          done
        fi
