name: "Terraform Apply"
description: "Run terraform apply"

inputs:
  aws_ecr_role_arn:
    description: "AWS Terraform role"
    required: true
    default: "arn:aws:iam::593673322979:role/github_oidc_role_terraform"
  aws_region:
    description: "AWS Region"
    required: true
    default: "us-west-1"
  terraform_version:
    description: 'The version of Terraform to use'
    required: true
    default: '1.5.7'
  auto_approve:
    description: 'Auto approve the terraform apply'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_ecr_role_arn }}
        aws-region: ${{ inputs.aws_region }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Initialize Terraform
      shell: bash
      run: terraform init
    - name: Terraform Apply
      shell: bash
      run: terraform apply -auto-approve=${{ inputs.auto_approve }}
