name: Deploy Python Lambda to S3
description: Deploy a Python Lambda function code to S3

inputs:
  name:
    description: 'Name of the lambda'
    required: true
  version:
    description: 'Version of the lambda'
    required: true
  s3_bucket:
    description: 'Name of the S3 bucket'
    required: true
  python_version:
    description: 'Python version to use'
    default: '3.11.9'
  poetry_version:
    description: 'Poetry version to use'
    default: '1.8.3'
  aws_ecr_role_arn:
    description: "AWS S3 role"
    required: true
    default: "arn:aws:iam::593673322979:role/github_oidc_role_read_write_s3"
  aws_region:
    description: "AWS Region"
    required: true
    default: "us-west-1"

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_ecr_role_arn }}
        aws-region: ${{ inputs.aws_region }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install Poetry
      shell: bash
      run: |
        pip install poetry==${{ inputs.poetry_version }}
    - name: Install dependencies
      shell: bash
      run: |
        poetry config --local virtualenvs.in-project true
        poetry install --only main --sync
    - name: Build Lambda package
      shell: bash
      run: |
        mkdir -p /tmp/lambda-package
        cp --recursive .venv/lib/python*/site-packages/* /tmp/lambda-package/
        cp --recursive . /tmp/lambda-package/
        cd /tmp/lambda-package/
        zip -r /tmp/${{ inputs.name }}_${{ inputs.version }}.zip *
    - name: Deploy to S3
      shell: bash
      run: |
        aws s3 cp /tmp/${{ inputs.name }}_${{ inputs.version }}.zip s3://${{ inputs.s3_bucket }}
