name: "Terraform Plan"
description: "Run terraform plan"

inputs:
  aws_ecr_role_arn:
    description: "AWS Terraform role"
    required: true
    default: "arn:aws:iam::593673322979:role/github_oidc_role_terraform"
  terraform_version:
    description: 'The version of Terraform to use'
    required: false
    default: 'v1.5.7'

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws_ecr_role_arn }}
        aws-region: ${{ inputs.aws_region }}
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
    - name: Initialize Terraform
      run: terraform init
    - name: Terraform Plan
      run: terraform plan
